// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable, dead_code, unnecessary_cast
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';
import 'package:core_location_fluttify/core_location_fluttify.dart';
import 'package:amap_core_fluttify/amap_core_fluttify.dart';

class _com_amap_api_location_AMapLocationListener_SUB extends java_lang_Object with com_amap_api_location_AMapLocationListener {}

mixin com_amap_api_location_AMapLocationListener on java_lang_Object {
  

  static com_amap_api_location_AMapLocationListener subInstance() => _com_amap_api_location_AMapLocationListener_SUB();

  static Future<com_amap_api_location_AMapLocationListener> anonymous__() async {
    final __result__ = await kAmapLocationFluttifyChannel.invokeMethod('com.amap.api.location.AMapLocationListener::createAnonymous__');
  
    final __object__ = AmapLocationFluttifyAndroidAs<com_amap_api_location_AMapLocationListener>(__result__)!;
  
    // handle callback
    MethodChannel('com.amap.api.location.AMapLocationListener::Callback@${__object__.refId}', kAmapLocationFluttifyMethodCodec)
        .setMethodCallHandler((methodCall) async {
          try {
            final args = methodCall.arguments as Map;
            switch (methodCall.method) {
              case 'onLocationChanged':
                // print log
                if (fluttifyLogEnabled) {
                  debugPrint('fluttify-dart-callback: __object__.onLocationChanged?.call([\'var1\':${args['var1']}])');
                }
            
                // handle the native call
                __object__.onLocationChanged?.call(AmapLocationFluttifyAndroidAs<com_amap_api_location_AMapLocation>(args['var1']));
                break;
              default:
                throw MissingPluginException('方法${methodCall.method}未实现');
                break;
            }
          } catch (e) {
            debugPrint(e.toString());
            rethrow;
          }
        });
  
    return __object__;
  }
  

  @override
  final String tag__ = 'amap_location_fluttify';

  

  

  Future<void> Function(com_amap_api_location_AMapLocation? var1)? onLocationChanged;
  
}

