//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

#import <Foundation/Foundation.h>
#import <AMapLocationKit/AMapLocationKit.h>

@protocol FlutterPluginRegistrar;

NS_ASSUME_NONNULL_BEGIN

@interface AMapGeoFenceManagerDelegate_Anonymous : NSObject<AMapGeoFenceManagerDelegate>

- (instancetype) initWithFlutterPluginRegistrar: (NSObject <FlutterPluginRegistrar> *) registrar;

@property(nonatomic) NSObject<FlutterPluginRegistrar>* registrar;

@end

NS_ASSUME_NONNULL_END

